-- Add new audit action types
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'LOGIN';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'LOGIN_FAILED';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'LOGOUT';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'SECURITY_ALERT';

-- Add new audit entity type
ALTER TYPE "EntityType" ADD VALUE IF NOT EXISTS 'FAMILY_CONFIG';
